### ISSUE TITLE
Multiple choice should not include the option 'MPA not listed'. 

### ISSUE THREAD

**Issue by leoniewalter** [courtiol/MPA_questionnaire#3]
I think the multiple choice dropdown is great, but then the option 'MPA not listed' should be a seperate item, to avoid the combination of selected existing MPAs and the option 'MPA not listed'. 
Maybe a new (single choice) item saying: One or more of the MPAs I am responding for is not listed ('yes, I am missing one or more MPAs'; 'no, I found (all )my MPA(s)') 
-> conditional for "yes": 
(Free text item) Please detail which MPA(s) are missing:
-> (mail address item): Please allow us to send you an updated survey including the MPAs currently missing (enter your mail address): 
Otherwise we might get info on what is missing, but no details on personell employed.

**Comment by courtiol** [comment]
Too complicated. I don't see the problem and that way I can easily make sure they answer the MPA question.
We won't ask the personnel numbers for each MPA (too complicated) but for all MPAs the person is responding for.
So I don't think this is an issue.
In practice, those cases should also rarely emerge.
